### PR TITLE
Multiplayer compatibility for 'Eject' button

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Not sure if anything else needs changes, but I did not really find anything that desynced the game.

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
Also, a quick note. If you don't want to include any additional dependencies, then I could patch this mod from the [Multiplayer Compatibility](https://github.com/rwmt/Multiplayer-Compatibility) project, in which case I'd appreciate if you extracted the code I did in the `EjectTarget` method, in the same (or similar) way I did. It would make it much cleaner to patch.

**Comment by Dakraid** [comment]
Sorry for the delay, for some reason Github did not send me the notification that I had a PR ready.

Anyways, I'm fine with the changes and will merge them in.

**Comment by Dakraid** [comment]
@SokyranTheDragon I did remove the dependency now in commit e9a4ac7, but kept the changes you made so it is possible to be patched.

**Comment by SokyranTheDragon** [comment]
Thanks for the help. I've made PR to the [Multiplayer Compatibility](https://github.com/rwmt/Multiplayer-Compatibility/pull/49) project, and it will most likely be included soon.

**Pull request merged**
